### ISSUE TITLE
WebError is not a contructor

### ISSUE THREAD

**Issue by NickNaso** [seeden/rbac#24]
Hi, 
i get this error using rbac with express
```bash
TypeError: WebError is not a constructor
    at /home/nicknaso/Desktop/pippo/node_modules/rbac/controllers/express.js:53:19
    at Layer.handle [as handle_request] (/home/nicknaso/Desktop/pippo/node_modules/express/lib/router/layer.js:95:5)
    at next (/home/nicknaso/Desktop/pippo/node_modules/express/lib/router/route.js:131:13)
    at Route.dispatch (/home/nicknaso/Desktop/pippo/node_modules/express/lib/router/route.js:112:3)
    at Layer.handle [as handle_request] (/home/nicknaso/Desktop/pippo/node_modules/express/lib/router/layer.js:95:5)
    at /home/nicknaso/Desktop/pippo/node_modules/express/lib/router/index.js:277:22
    at Function.process_params (/home/nicknaso/Desktop/pippo/node_modules/express/lib/router/index.js:330:12)
    at next (/home/nicknaso/Desktop/pippo/node_modules/express/lib/router/index.js:271:10)
    at jsonParser (/home/nicknaso/Desktop/pippo/node_modules/body-parser/lib/types/json.js:103:7)
    at Layer.handle [as handle_request] (/home/nicknaso/Desktop/pippo/node_modules/express/lib/router/layer.js:95:5)
```

I checked the module internally and in the controller ```rbac/controllers/express.js``` and **web-error** module is imported as repoterd below:
```js
var WebError = require('web-error');
```
instead in your git repo it's imported in this way:
```js
var WebError = require('web-error').default;
```
I think you need to redeploy the module on npm.

**Comment by seeden** [comment]
weberror was removed from this package
