### ISSUE TITLE
Issue using rbac.getRole

### ISSUE THREAD

**Issue by Bibeknam** [seeden/rbac#6]
When I use <code>rbac.getRole</code>, each time I get the following error.

```
/Users/bibeksubedi/Personal/Projects/usermodule/node_modules/rbac/lib/base.js:19
		return cb(null, this);	
		       ^
TypeError: undefined is not a function
    at Role.Base (/Users/bibeksubedi/Personal/Projects/usermodule/node_modules/rbac/lib/base.js:19:10)
    at new Role (/Users/bibeksubedi/Personal/Projects/usermodule/node_modules/rbac/lib/role.js:16:7)
    at convertToInstance (/Users/bibeksubedi/Personal/Projects/usermodule/node_modules/rbac/lib/storage/mongoose.js:44:10)
    at Promise.<anonymous> (/Users/bibeksubedi/Personal/Projects/usermodule/node_modules/rbac/lib/storage/mongoose.js:182:12)
    at Promise.<anonymous> (/Users/bibeksubedi/Personal/Projects/usermodule/node_modules/mongoose/node_modules/mpromise/lib/promise.js:177:8)
    at Promise.emit (events.js:107:17)
    at Promise.emit (/Users/bibeksubedi/Personal/Projects/usermodule/node_modules/mongoose/node_modules/mpromise/lib/promise.js:84:38)
    at Promise.fulfill (/Users/bibeksubedi/Personal/Projects/usermodule/node_modules/mongoose/node_modules/mpromise/lib/promise.js:97:20)
    at /Users/bibeksubedi/Personal/Projects/usermodule/node_modules/mongoose/lib/query.js:1400:13
    at model.Document.init (/Users/bibeksubedi/Personal/Projects/usermodule/node_modules/mongoose/lib/document.js:250:11)
```
My suspect is in mongoose.js at line 44, where Role constructor is called without callback.

**Comment by seeden** [comment]
Can you try latest version (3.0.0)? It is completely rewritten.

**Comment by Bibeknam** [comment]
Yes I have updated but documentation doesn't work anymore. Do you have any example using this change?

**Comment by seeden** [comment]
I have fixed and updated documentation too

**Comment by seeden** [comment]
This issue was fixed. I am closing it
